=== PANJiawen/XML/master.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>

<!ENTITY % tabs "table | tr | th | td">
<!ENTITY % content "p | a | b | i" >
<!ENTITY % lists "ul | li | ol | dl | dt | dd" >
<!ENTITY % mise_en_forme  "%content; | %tabs; | %lists;" >

<!ELEMENT p ( #PCDATA | %mise_en_forme;  )* >
<!ELEMENT b ( #PCDATA | %mise_en_forme;  )* >
<!ELEMENT i ( #PCDATA | %mise_en_forme;  )* >
<!ELEMENT a ( #PCDATA | %mise_en_forme;  )* >
<!ATTLIST a
  href CDATA #IMPLIED >
<!ELEMENT ul ( #PCDATA | %mise_en_forme;  )* >
<!ELEMENT li ( #PCDATA | %mise_en_forme;  )* >
<!ELEMENT ol ( #PCDATA | %mise_en_forme;  )* >
<!ELEMENT dl ( #PCDATA | %mise_en_forme;  )* >
<!ELEMENT dt ( #PCDATA | %mise_en_forme;  )* >
<!ELEMENT dd ( #PCDATA | %mise_en_forme;  )* >

<!ELEMENT table ( #PCDATA | tr| %content; )* >
<!ELEMENT tr ( #PCDATA | th| td| %content; )* >
<!ELEMENT th ( #PCDATA | %mise_en_forme;  )* >
<!ELEMENT td ( #PCDATA | %mise_en_forme;  )* >

<!ELEMENT master	(intervenant+, unite+, parcours+)>
<!ELEMENT intervenant	(nom, adresse, site, telephone, etablissement)>
<!ELEMENT unite		(nom, ref-intervenant*, nombreCredits, resume?, plan?, lieu?)>
<!ELEMENT parcours	(nom, ref-responsable?, description?, branche+)>
<!ELEMENT branche	(nom, ref-responsable+, description+, debouche+, lieu+, semestre*, competences*, connaissances*, politique-stages*, ens-delocalise*, aspects-recherche*, modalites-pedago*, condition-adm*, poursuite-etud*)>
<!ELEMENT semestre	(bloc+)>
<!ELEMENT bloc		(ref-unite+)>

<!ELEMENT nom			(#PCDATA)>
<!ELEMENT ref-intervenant	(#PCDATA)>
<!ELEMENT nombreCredits		(#PCDATA)>
<!ELEMENT resume	(#PCDATA | %mise_en_forme;)*>
<!ELEMENT plan			(#PCDATA)>
<!ELEMENT lieu			(#PCDATA)>

<!ELEMENT adresse		(#PCDATA)>
<!ELEMENT site			(#PCDATA)>
<!ELEMENT telephone		(#PCDATA)>
<!ELEMENT etablissement		(#PCDATA)>

<!ELEMENT ref-responsable	(#PCDATA)>
<!ELEMENT description		(#PCDATA)>
<!ELEMENT debouche		(#PCDATA)>

<!ELEMENT ref-unite		(#PCDATA)>
<!ELEMENT obligatoire		(#PCDATA)>
<!ELEMENT option		(#PCDATA)>

<!ELEMENT competences		(#PCDATA)>
<!ELEMENT connaissances		(#PCDATA)>
<!ELEMENT politique-stages	(#PCDATA)>
<!ELEMENT ens-delocalise	(#PCDATA)>
<!ELEMENT aspects-recherche	(#PCDATA)>
<!ELEMENT modalites-pedago	(#PCDATA)>
<!ELEMENT condition-adm		(#PCDATA | %mise_en_forme;)*>
<!ELEMENT poursuite-etud	(#PCDATA)>

<!ATTLIST intervenant id ID #IMPLIED>
<!ATTLIST unite id ID #IMPLIED>
<!ATTLIST ref-intervenant ref IDREF #REQUIRED>
<!ATTLIST ref-responsable ref IDREF #REQUIRED>
<!ATTLIST ref-unite ref IDREF #REQUIRED>
<!ATTLIST semestre numero CDATA #REQUIRED>
<!ATTLIST bloc role (obligatoire|option|bonus) #IMPLIED>
<!ATTLIST branche finalite (professionnelle|recherche) #IMPLIED>

=== PANJiawen/XML/master.xml
<?xml version="1.0"?>
<!DOCTYPE master SYSTEM "master.dtd">
<master>
   <intervenant id="morin">
      <nom>Remi MORIN</nom>
      <adresse>remi.morin@univ-amu.fr</adresse>
      <site>www.remi.morin.perso.luminy.univ-amu.fr/</site>
      <telephone>0491829394</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="massat">
      <nom>Jean-Luc Massat</nom>
      <adresse>jean-luc.massat@univ-amu.fr</adresse>
      <site>www.jean-luc.massat.perso.luminy.univ-amu.fr/</site>
      <telephone></telephone>
      <etablissement></etablissement>
   </intervenant>
   <intervenant id="reynier">
      <nom>Pierre-Alain REYNIER</nom>
      <adresse>reynier@univ-amu.fr</adresse>
      <site>www.reynier.perso.luminy.univ-amu.fr/</site>
      <telephone>0491829313</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseillex</etablissement>
   </intervenant>
   <intervenant id="agopian">
      <nom>Roland AGOPIAN</nom>
      <adresse>roland.agopian@univ-amu.fr</adresse>
      <site>www.agopian.perso.luminy.univ-amu.fr</site>
      <telephone>0413551364</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="artieres">
      <nom>Thierry ARTIÈRES</nom>
      <adresse>thierry.artieres@lif.univ-mrs.fr</adresse>
      <site>www.artheries.perso.luminy.univ-amu.fr</site>
      <telephone></telephone>
      <etablissement>École Centrale Marseille</etablissement>
   </intervenant>
   <intervenant id="bechet">
      <nom>Frederic BECHET</nom>
      <adresse>frederic.bechet@univ-amu.fr</adresse>
      <site></site>
      <telephone>0491829559</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="bertolissi">
      <nom>Clara BERTOLISSI</nom>
      <adresse>clara.bertolissi@univ-amu.fr</adresse>
      <site></site>
      <telephone>0491829527</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="boucelma">
      <nom>Omar BOUCELMA</nom>
      <adresse>omar.boucelma@univ-amu.fr</adresse>
      <site></site>
      <telephone>0491056053</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="broche">
      <nom>Martine BROCHE</nom>
      <adresse>martine.broche@univ-amu.fr</adresse>
      <site></site>
      <telephone></telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="creignou">
      <nom>Nadia CREIGNOU</nom>
      <adresse>nadia.creignou@univ-amu.fr</adresse>
      <site></site>
      <telephone>0491829480</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="demongodin">
      <nom>Isabelle DEMONGODIN</nom>
      <adresse>isabel.demongodin@univ-amu.fr</adresse>
      <site>http://www.lsis.org/isabel_demongodin</site>
      <telephone>0491056077</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="estellon">
      <nom>Bertrand ESTELLON</nom>
      <adresse>bertrand.estellon@univ-amu.fr</adresse>
      <site></site>
      <telephone>0491829492</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="favre">
      <nom>Benoit FAVRE</nom>
      <adresse>benoit.favre@univ-amu.fr</adresse>
      <site></site>
      <telephone></telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="godard">
      <nom>Emmanuel GODARD</nom>
      <adresse>emmanuel.godard@univ-amu.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~emmanuel.godard/</site>
      <telephone></telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="habet">
      <nom>Djamal HABET</nom>
      <adresse>djamal.habet@univ-amu.fr</adresse>
      <site>http://www.lsis.org/habetd/</site>
      <telephone>0491288321</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="jamet">
      <nom>Line JAMET</nom>
      <adresse>line.jakubiec@univ-amu.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~line.jakubiec/</site>
      <telephone>0491829311</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="labourel">
      <nom>Arnaud LABOUREL</nom>
      <adresse>arnaud.labourel@univ-amu.fr</adresse>
      <site>pageperso.lif.univ-mrs.fr/~arnaud.labourel/</site>
      <telephone>0491829195</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="lai">
      <nom>Claude LAI</nom>
      <adresse>claude.lai@univ-amu.fr</adresse>
      <site></site>
      <telephone>0491829316</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="lugiez">
      <nom>Denis LUGIEZ</nom>
      <adresse>denis.lugiez@univ-amu.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~denis.lugiez/</site>
      <telephone>0413551333</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="michel">
      <nom>Stephane MICHEL</nom>
      <adresse></adresse>
      <site></site>
      <telephone></telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="novelli">
      <nom>Noel NOVELLI</nom>
      <adresse>noel.novelli@univ-amu.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~noel.novelli/</site>
      <telephone>0491829370</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="olive">
      <nom>Frederic OLIVE</nom>
      <adresse>frederic.olive@univ-amu.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~frederic.olive/</site>
      <telephone>0491829000</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="olivetti">
      <nom>Nicola OLIVETTI</nom>
      <adresse>nicola.olivetti@univ-amu.fr</adresse>
      <site>http://www.lsis.org/olivetti/</site>
      <telephone>0486091046</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="chabarot">
      <nom>Lydie RENE CHABAROT</nom>
      <adresse>lydie.rene@univ-amu.fr</adresse>
      <site></site>
      <telephone></telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="risch">
      <nom>Sylvie RISCH</nom>
      <adresse>sylvie.risch@univ-amu.fr</adresse>
      <site></site>
      <telephone>0491829316</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="sabatier">
      <nom>Claude SABATIER</nom>
      <adresse>claude.sabatier@univ-amu.fr</adresse>
      <site></site>
      <telephone>0491829481</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="sellami">
      <nom>Sana SELLAMI</nom>
      <adresse>sana.sellami@univ-amu.fr</adresse>
      <site>http://www.lsis.org/sellamis/</site>
      <telephone>0491056057</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="vaxes">
      <nom>Yann VAXES</nom>
      <adresse>yann.vaxes@univ-amu.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~yann.vaxes/</site>
      <telephone>0491829196</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
  <intervenant id="santocanale">
      <nom>Luigi Santocanale</nom>
      <adresse>luigi.santocanale@lif.univ-mrs.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~luigi.santocanale/</site>
      <telephone>0491829275 </telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="arrighi">
      <nom>Pablo Arrighi</nom>
      <adresse>pablo.arrighi@lif.univ-mrs.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~pablo.arrighi//</site>
      <telephone>0486090450</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="niebert">
      <nom>Peter Niebert</nom>
      <adresse>peter.niebert@univ-amu.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~peter.niebert/</site>
      <telephone>0486090493</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="jegou">
      <nom>Philippe JEGOU</nom>
      <adresse>philippe.jegou@univ-amu.fr</adresse>
      <site>http://www.lsis.org/philippe_jegou</site>
      <telephone>0491288937</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="kadri">
      <nom>Hachem Kadri</nom>
      <adresse>hachem.kadri@lif.univ-mrs.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~hachem.kadri/</site>
      <telephone>0413551322</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
   </intervenant>
   <intervenant id="couetoux">
      <nom>Basile Couetoux</nom>
      <adresse>basile.couetoux@lif.univ-mrs.fr</adresse>
      <site>http://pageperso.lif.univ-mrs.fr/~basile.couetoux/</site>
      <telephone>0491829296</telephone>
      <etablissement>UFR Sciences, Université d'Aix-Marseille</etablissement>
